name: 'my_project'
version: '1.0.0'
config-version: 2

profile: 'openavm-dbt'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  openavm-dbt:
    staging:
      +materialized: view
    output:
      +materialized: external
      +location: './output/parquet/'
      +format: parquet
